const ENTRY_DEFS = [
  {id:'testcase_gen',name:'测试用例生成',icon:'cases',triggers:['需求','验收','用例','场景','测试点'],required:['需求背景','验收标准'],knowledge:['业务规则库','接口异常库','历史 Bug 库'],workflow:['校验输入','拆解测试点','覆盖正常/异常/边界','生成结构化用例','标记人工复核']},
  {id:'bug_analysis',name:'Bug 分析',icon:'bug',triggers:['bug','缺陷','复现','实际结果','预期结果','报错','异常'],required:['问题标题','复现步骤','实际结果','预期结果','环境'],knowledge:['历史 Bug 库','日志规律库','SQL 经验库','业务规则库'],workflow:['校验输入','描述现象','识别影响模块','给出日志方向','给出 SQL 方向','检索历史 Bug','生成回归范围','判断风险','标记人工复核']},
  {id:'log_triage',name:'日志排查',icon:'logs',triggers:['日志','traceid','exception','error','timeout','堆栈','调用链','lock wait'],required:['日志或 traceId','时间范围','运行环境'],knowledge:['日志规律库','历史 Bug 库'],workflow:['提取关键字','识别异常','还原调用链','定位可疑模块','匹配历史规律','给出排查建议','标记证据缺口']},
  {id:'sql_analysis',name:'SQL 分析',icon:'sql',triggers:['sql','select ','update ','insert ','delete ','join ','explain','索引','慢查询','数据库'],required:['SQL 文本','分析目标'],knowledge:['SQL 经验库','压测经验库'],workflow:['识别风险','检查 WHERE','给出索引验证方向','分析慢查询','检查 JOIN','检查 ORDER BY','判断性能风险','建议 EXPLAIN 验证']},
  {id:'regression_list',name:'回归清单',icon:'regression',triggers:['回归','影响范围','改动模块','发布范围','变更范围'],required:['版本或变更内容','影响模块'],knowledge:['回归规则库','历史 Bug 库'],workflow:['识别直接变更','扩展上下游','还原业务链路','检索历史 Bug','评估风险','生成必测/建议项','人工复核']},
  {id:'test_report',name:'测试报告',icon:'report',triggers:['测试报告','上线结论','发布报告','质量结论'],required:['版本','测试范围','执行结果'],knowledge:['业务规则库','历史 Bug 库','回归规则库'],workflow:['汇总测试范围','统计执行结果','汇总缺陷','识别风险模块','整理遗留问题','生成上线建议','人工审批']},
  {id:'prompt_test',name:'Prompt 测试',icon:'prompt',triggers:['prompt','提示词','模型输出','回答质量','幻觉'],required:['Prompt 文本','预期输出或评价标准'],knowledge:[],workflow:['读取 Prompt','准备样例','逐项运行','对照 Schema','检查事实与幻觉','记录差异','人工判定']}
];
const DEFAULT_ORDER=ENTRY_DEFS.map(x=>x.id);
const now=()=>new Date().toISOString();
const parse=(v,f={})=>{try{return JSON.parse(v)}catch{return f}};
const json=v=>JSON.stringify(v??{});
const makeId=p=>`${p}_${crypto.randomUUID().slice(0,8)}`;
const camel=row=>row?Object.fromEntries(Object.entries(row).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v])):null;

function normalizeAsset(row){const x=camel(row);x.triggers=parse(x.triggersJson,[]);x.required=parse(x.requiredJson,[]);x.knowledge=parse(x.knowledgeJson,[]);x.workflow=parse(x.workflowJson,[]);delete x.triggersJson;delete x.requiredJson;delete x.knowledgeJson;delete x.workflowJson;return x}
function normalizeRun(row){const x=camel(row);for(const k of ['routesJson','inputJson','resultJson','missingJson','reviewJson','evidenceJson']){x[k.replace('Json','')]=parse(x[k],k==='routesJson'||k==='missingJson'||k==='evidenceJson'?[]:{});delete x[k]}return x}
function fieldPresent(text,field){const rules={
  '问题标题':/.{5,}/,'复现步骤':/复现|步骤|操作|点击|请求/,'实际结果':/实际|现象|仍为|报错|失败/,'预期结果':/预期|应该|应为/,'环境':/环境|staging|test|prod|生产|测试环境/,
  '日志或 traceId':/日志|trace\s?id|exception|error|timeout|堆栈/i,'时间范围':/\d{1,2}:\d{2}|\d{4}-\d{1,2}-\d{1,2}|时间/,'运行环境':/环境|staging|test|prod|生产/,
  'SQL 文本':/select |update |insert |delete |join |explain /i,'分析目标':/分析|排查|优化|慢|风险|一致性/,
  '需求背景':/需求|背景|功能|规则/,'验收标准':/验收|预期|应当|必须/,'版本或变更内容':/版本|v\d|变更|改动/,'影响模块':/模块|支付|订单|账户|接口/,
  '版本':/版本|v\d/,'测试范围':/范围|模块|用例|回归/,'执行结果':/通过|失败|阻塞|执行/,'Prompt 文本':/prompt|提示词/i,'预期输出或评价标准':/预期|标准|schema|格式/i
};return rules[field]?.test(text)||false}
function routeText(text,selected=[]){const lower=text.toLowerCase();let ids=ENTRY_DEFS.filter(e=>e.triggers.some(t=>lower.includes(t.toLowerCase()))).map(e=>e.id);selected.forEach(id=>{if(!ids.includes(id))ids.push(id)});if(!ids.length)ids=['bug_analysis'];ids.sort((a,b)=>DEFAULT_ORDER.indexOf(a)-DEFAULT_ORDER.indexOf(b));return ids}
function buildOutput(id,text,risk){
  const common={risk_level:risk,human_review_points:['确认事实与引用依据','P0/P1 风险和上线结论必须由测试人最终确认'],need_more_info:[]};
  if(id==='bug_analysis')return {...common,phenomenon:text.slice(0,180),affected_modules:['根据已选三级模块确认'],possible_causes:['从现象推测存在状态同步或事务边界异常，尚需证据验证'],recommended_logs:['按 traceId 串联入口、消息消费和数据库更新日志'],recommended_sql:['核对业务主表与流水表状态、金额及更新时间'],related_history_bugs:['仅展示实际检索命中的知识，不编造 Bug 编号'],regression_scope:['直接变更模块','上下游状态同步','失败与重复请求场景']};
  if(id==='log_triage')return {...common,anomaly_summary:'已提取异常关键词与时间线，根因仍需结合完整上下文确认',timeline:['接收用户证据','定位首个异常片段','向上下游扩展调用链'],suspect_modules:['待结合 traceId 与模块配置确认'],suggestions:['补充异常前后至少 30 行日志','核对同 traceId 的入口与消费端日志']};
  if(id==='sql_analysis')return {...common,risks:['需要检查过滤条件、JOIN、排序和事务一致性'],where_review:'确认过滤条件是否命中预期数据范围',index_advice:'仅作为验证方向；需结合 EXPLAIN、数据量和基数判断',explain_suggestions:['在测试环境执行 EXPLAIN/EXPLAIN ANALYZE','保存执行计划与耗时证据']};
  if(id==='regression_list')return {...common,must_regression:['直接变更功能','核心成功链路','失败链路','重复请求与幂等','上下游状态同步','历史高风险缺陷'],suggested_regression:['边界数据','权限与兼容性'],completion_rule:'至少 6 个必回归项，经人工确认后执行'};
  if(id==='testcase_gen')return {...common,coverage:['正常','异常','边界','权限','幂等'],case_format:['标题','前置条件','步骤','预期结果','优先级'],suggestions:['生成后按功能与子模块入用例库']};
  if(id==='test_report')return {...common,sections:['测试范围','执行结果','缺陷统计','风险模块','遗留问题','上线结论'],release_decision:'待测试负责人审批，AI 不做最终上线批准'};
  return {...common,checks:['Schema 完整性','事实准确性','引用可追溯','幻觉风险'],decision:'待人工最终判定'};
}

export function createWorkbench(db){
  db.exec(`
    CREATE TABLE IF NOT EXISTS workbench_assets (id TEXT PRIMARY KEY, name TEXT NOT NULL, icon TEXT NOT NULL, triggers_json TEXT NOT NULL, required_json TEXT NOT NULL, knowledge_json TEXT NOT NULL, workflow_json TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT '已发布', updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS workflow_runs (id TEXT PRIMARY KEY, title TEXT NOT NULL, main_route TEXT NOT NULL, routes_json TEXT NOT NULL, module_id TEXT, status TEXT NOT NULL, risk TEXT NOT NULL, input_json TEXT NOT NULL, result_json TEXT NOT NULL, missing_json TEXT NOT NULL, review_json TEXT NOT NULL, evidence_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS workflow_run_steps (id TEXT PRIMARY KEY, run_id TEXT NOT NULL, route_id TEXT NOT NULL, step_order INTEGER NOT NULL, step_name TEXT NOT NULL, status TEXT NOT NULL, output_json TEXT NOT NULL DEFAULT '{}', started_at TEXT, completed_at TEXT, FOREIGN KEY(run_id) REFERENCES workflow_runs(id));
    CREATE TABLE IF NOT EXISTS validation_cases (id TEXT PRIMARY KEY, name TEXT NOT NULL, input_text TEXT NOT NULL, expected_routes_json TEXT NOT NULL, expected_rules_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT '待验证', last_result_json TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL);
  `);
  const ins=db.prepare('INSERT OR IGNORE INTO workbench_assets VALUES(?,?,?,?,?,?,?,?,?,?)');
  ENTRY_DEFS.forEach(e=>ins.run(e.id,e.name,e.icon,json(e.triggers),json(e.required),json(e.knowledge),json(e.workflow),1,'已发布',now()));
  const sample='支付成功后订单仍为待支付，staging 环境 v2.8.3。复现步骤：完成支付后等待 30 秒查询订单；实际结果仍为待支付，预期订单应为已支付。traceId=demo-1024，日志出现 Lock wait timeout。请给出 SQL 排查方向和回归范围。';
  db.prepare('INSERT OR IGNORE INTO validation_cases VALUES(?,?,?,?,?,?,?,?)').run('val_payment','支付成功但订单未支付 · 完整材料',sample,json(['bug_analysis','log_triage','sql_analysis','regression_list']),json(['不跳结论','根因需证据','至少 6 个必回归项','P0/P1 人工复核']),'待验证',json({}),now());

  const send=(res,status,payload)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(payload))};
  const body=async req=>{const chunks=[];for await(const c of req)chunks.push(c);return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}};
  const assets=()=>db.prepare('SELECT * FROM workbench_assets ORDER BY rowid').all().map(normalizeAsset);
  const getRun=id=>{const row=db.prepare('SELECT * FROM workflow_runs WHERE id=?').get(id);if(!row)return null;const run=normalizeRun(row);run.steps=db.prepare('SELECT * FROM workflow_run_steps WHERE run_id=? ORDER BY step_order').all(id).map(s=>{const x=camel(s);x.output=parse(x.outputJson,{});delete x.outputJson;return x});return run};
  async function handle(req,res,url,parts){
    if(parts[1]!=='workbench')return false;
    if(req.method==='GET'&&parts[2]==='config')return send(res,200,{entries:assets(),dispatch:{multiRoutePolicy:'sequential_when_matched',defaultOrder:DEFAULT_ORDER},rules:['不跳步骤','证据不足时明确标记','不编造知识标题或 Bug 编号','AI 不批准上线','P0/P1 与 Prompt 通过需人工复核']});
    if(req.method==='POST'&&parts[2]==='preflight'){const d=await body(req),text=String(d.text||''),routes=routeText(text,d.selectedRoutes||[]),all=assets();const matched=routes.map((id,i)=>{const e=all.find(x=>x.id===id);const missing=e.required.filter(f=>!fieldPresent(text,f));return{...e,role:i===0?'主任务':'辅助任务',missing,completeness:Math.round((e.required.length-missing.length)/Math.max(1,e.required.length)*100)}});return send(res,200,{routes:matched,mainRoute:routes[0],missing:[...new Set(matched.flatMap(x=>x.missing))],canRun:Boolean(text.trim()),policy:'sequential_when_matched'});}
    if(req.method==='POST'&&parts[2]==='runs'&&!parts[3]){const d=await body(req),text=String(d.text||'').trim();if(!text)return send(res,400,{error:'请输入待分析内容'});const routes=routeText(text,d.selectedRoutes||[]),all=assets(),matched=routes.map(id=>all.find(x=>x.id===id)),missing=[...new Set(matched.flatMap(e=>e.required.filter(f=>!fieldPresent(text,f))))],risk=/生产|资损|重复扣款|数据丢失|安全|p0/i.test(text)?'P0':/失败|异常|超时|锁等待|lock wait/i.test(text)?'P1':'P2',runId=makeId('run'),ts=now();const result={sections:{},routeSummary:matched.map((e,i)=>({id:e.id,name:e.name,role:i===0?'主任务':'辅助任务',knowledge:e.knowledge}))};matched.forEach(e=>result.sections[e.id]=buildOutput(e.id,text,risk));Object.values(result.sections).forEach(o=>o.need_more_info=missing);const review={required:risk==='P0'||risk==='P1'||routes.includes('prompt_test'),status:'待复核',checks:['任务识别是否准确','证据与结论是否匹配','风险等级是否合理','输出格式是否完整']};db.prepare('INSERT INTO workflow_runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(runId,d.title||text.split(/[。\n]/)[0].slice(0,42),routes[0],json(routes),d.moduleId||null,missing.length?'待补充':'待复核',risk,json({text,attachments:d.attachments||[]}),json(result),json(missing),json(review),json(['用户原始输入',...matched.flatMap(e=>e.knowledge.map(k=>`知识库：${k}`))]),ts,ts);let order=1;const stepIns=db.prepare('INSERT INTO workflow_run_steps VALUES(?,?,?,?,?,?,?,?,?)');matched.forEach(e=>e.workflow.forEach(name=>stepIns.run(makeId('step'),runId,e.id,order++,name,'已完成',json({note:'按工作流顺序执行',evidence:'用户输入与可用知识映射'}),ts,ts)));return send(res,201,getRun(runId));}
    if(req.method==='GET'&&parts[2]==='runs'&&!parts[3]){const page=Math.max(1,Number(url.searchParams.get('page')||1)),pageSize=[20,50,100].includes(Number(url.searchParams.get('pageSize')))?Number(url.searchParams.get('pageSize')):20,q=(url.searchParams.get('q')||'').trim(),status=url.searchParams.get('status')||'',clauses=[],params=[];if(q){clauses.push('(title LIKE ? OR input_json LIKE ?)');params.push(`%${q}%`,`%${q}%`)}if(status){clauses.push('status=?');params.push(status)}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=db.prepare(`SELECT COUNT(*) n FROM workflow_runs ${where}`).get(...params).n,rows=db.prepare(`SELECT * FROM workflow_runs ${where} ORDER BY updated_at DESC LIMIT ? OFFSET ?`).all(...params,pageSize,(page-1)*pageSize).map(normalizeRun);return send(res,200,{items:rows,page,pageSize,total,pages:Math.max(1,Math.ceil(total/pageSize))});}
    if(req.method==='GET'&&parts[2]==='runs'&&parts[3]){const run=getRun(parts[3]);return run?send(res,200,run):send(res,404,{error:'执行记录不存在'});}
    if(req.method==='PATCH'&&parts[2]==='runs'&&parts[3]){const d=await body(req),row=db.prepare('SELECT * FROM workflow_runs WHERE id=?').get(parts[3]);if(!row)return send(res,404,{error:'执行记录不存在'});const review=parse(row.review_json,{});if(d.action==='approve'){review.status='已复核';review.note=d.note||'人工确认通过';review.reviewedAt=now()}if(d.action==='reject'){review.status='已驳回';review.note=d.note||'请补充证据';review.reviewedAt=now()}const status=d.action==='approve'?'已完成':d.action==='reject'?'待补充':d.status||row.status;db.prepare('UPDATE workflow_runs SET status=?,review_json=?,updated_at=? WHERE id=?').run(status,json(review),now(),parts[3]);return send(res,200,getRun(parts[3]));}
    if(req.method==='GET'&&parts[2]==='assets')return send(res,200,{items:assets()});
    if(req.method==='PATCH'&&parts[2]==='assets'&&parts[3]){const d=await body(req),row=db.prepare('SELECT * FROM workbench_assets WHERE id=?').get(parts[3]);if(!row)return send(res,404,{error:'工作台资产不存在'});db.prepare('UPDATE workbench_assets SET triggers_json=?,required_json=?,knowledge_json=?,workflow_json=?,version=version+1,status=?,updated_at=? WHERE id=?').run(json(d.triggers??parse(row.triggers_json,[])),json(d.required??parse(row.required_json,[])),json(d.knowledge??parse(row.knowledge_json,[])),json(d.workflow??parse(row.workflow_json,[])),d.status??row.status,now(),parts[3]);return send(res,200,normalizeAsset(db.prepare('SELECT * FROM workbench_assets WHERE id=?').get(parts[3])));}
    if(req.method==='GET'&&parts[2]==='validations')return send(res,200,{items:db.prepare('SELECT * FROM validation_cases ORDER BY updated_at DESC').all().map(r=>{const x=camel(r);x.expectedRoutes=parse(x.expectedRoutesJson,[]);x.expectedRules=parse(x.expectedRulesJson,[]);x.lastResult=parse(x.lastResultJson,{});delete x.expectedRoutesJson;delete x.expectedRulesJson;delete x.lastResultJson;return x})});
    if(req.method==='POST'&&parts[2]==='validations'&&parts[3]){const row=db.prepare('SELECT * FROM validation_cases WHERE id=?').get(parts[3]);if(!row)return send(res,404,{error:'验证案例不存在'});const actual=routeText(row.input_text),expected=parse(row.expected_routes_json,[]),passed=expected.every(x=>actual.includes(x)),result={actualRoutes:actual,expectedRoutes:expected,passed,checkedAt:now(),rules:parse(row.expected_rules_json,[])};db.prepare('UPDATE validation_cases SET status=?,last_result_json=?,updated_at=? WHERE id=?').run(passed?'通过':'失败',json(result),now(),parts[3]);return send(res,200,result);}
    return send(res,404,{error:'工作台接口不存在'});
  }
  return {handle};
}
