import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Bot, Check, ChevronDown, ChevronRight, ClipboardCheck, Database, FileBarChart, GitBranch, ListChecks, Loader2, Play, RefreshCw, Save, Search, Settings2, ShieldCheck, Sparkles, SquareTerminal, TestTube2, X } from 'lucide-react';

type Row=Record<string,any>;
const api=async(path:string,options?:RequestInit)=>{const r=await fetch(`/api/workbench${path}`,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');return d};
const post=(path:string,data:Row)=>api(path,{method:'POST',body:JSON.stringify(data)});
const patch=(path:string,data:Row)=>api(path,{method:'PATCH',body:JSON.stringify(data)});
const routeIcon=(id:string)=>{const C=id==='testcase_gen'?ListChecks:id==='bug_analysis'?AlertTriangle:id==='log_triage'?SquareTerminal:id==='sql_analysis'?Database:id==='regression_list'?ClipboardCheck:id==='test_report'?FileBarChart:TestTube2;return <C/>};
const dateTime=(v:string)=>new Date(v).toLocaleString('zh-CN',{hour12:false});

export function AssistantPage({bootstrap,notify}:any){
  const [config,setConfig]=useState<Row>({entries:[],rules:[]}),[selected,setSelected]=useState<string[]>([]),[text,setText]=useState(''),[moduleId,setModuleId]=useState(bootstrap.modules[0]?.id||''),[preflight,setPreflight]=useState<Row|null>(null),[run,setRun]=useState<Row|null>(null),[busy,setBusy]=useState(false);
  useEffect(()=>{api('/config').then(setConfig).catch(e=>notify(e.message))},[]);
  const selectedEntries=useMemo(()=>config.entries.filter((x:Row)=>selected.includes(x.id)),[config,selected]);
  async function inspect(){if(!text.trim())return notify('请先输入待分析内容');setBusy(true);try{setPreflight(await post('/preflight',{text,selectedRoutes:selected}));setRun(null)}catch(e:any){notify(e.message)}finally{setBusy(false)}}
  async function execute(){if(!text.trim())return notify('请先输入待分析内容');setBusy(true);try{const r=await post('/runs',{text,moduleId,selectedRoutes:selected});setRun(r);setPreflight(r);notify('已按路由顺序完成分析，等待人工复核')}catch(e:any){notify(e.message)}finally{setBusy(false)}}
  function sample(){setText('支付成功后订单仍为待支付，staging 环境 v2.8.3。复现步骤：完成支付后等待 30 秒查询订单；实际结果仍为待支付，预期订单应为已支付。traceId=demo-1024，日志出现 Lock wait timeout。请给出 SQL 排查方向和回归范围。');setSelected([]);setPreflight(null);setRun(null)}
  return <div className="page stack wb-page"><div className="page-intro"><div><span className="wb-kicker">AI TEST ASSISTANT</span><h2>一句话发起完整测试分析</h2><p>自动识别主任务与辅助任务，按工作流顺序执行；证据不足时只提示补充，不猜测根因。</p></div><button className="button" onClick={sample}><Sparkles/>载入支付异常示例</button></div>
    <section className="panel wb-route-picker"><div className="panel-title"><div><h3>可选任务入口</h3><p>可不勾选交给系统识别，也可勾选指定要同时执行的任务</p></div><span className="wb-id">sequential_when_matched</span></div><div className="wb-entry-grid">{config.entries.map((e:Row)=><button key={e.id} className={selected.includes(e.id)?'selected':''} onClick={()=>setSelected(v=>v.includes(e.id)?v.filter(x=>x!==e.id):[...v,e.id])}><span className="wb-entry-icon">{routeIcon(e.id)}</span><span><strong>{e.name}</strong><small>{e.id}</small></span><i>{selected.includes(e.id)?<Check/>:<span/>}</i></button>)}</div></section>
    <div className="two-col wb-input-grid"><section className="panel"><div className="panel-title"><div><h3>智能输入</h3><p>支持整段材料；详细字段可在识别后逐项补充</p></div><span className="wb-count">{text.length} 字</span></div><label className="field"><span>项目 / 模块 / 子模块</span><select value={moduleId} onChange={e=>setModuleId(e.target.value)}>{bootstrap.modules.filter((m:Row)=>m.status==='启用').map((m:Row)=><option key={m.id} value={m.id}>{m.projectName} / {m.moduleName} / {m.submoduleName}</option>)}</select></label><label className="field"><span>问题、需求或发布材料</span><textarea className="large wb-textarea" value={text} onChange={e=>{setText(e.target.value);setPreflight(null);setRun(null)}} placeholder="粘贴需求、Bug 现象、复现步骤、日志、SQL、版本改动或测试结果…"/></label><div className="wb-upload-note">附件入口已预留；首版先保存文本与文件名，敏感日志请脱敏后粘贴。</div><div className="smart-actions"><button className="button" onClick={inspect} disabled={busy}>{busy?<Loader2 className="spin"/>:<Search/>}识别任务与缺项</button><button className="button primary" onClick={execute} disabled={busy||!text.trim()}><Play/>按流程执行</button></div></section>
      <aside className="panel wb-preflight"><div className="panel-title"><div><h3>执行前检查</h3><p>{preflight?'识别结果已更新':'等待输入材料'}</p></div>{preflight&&<span className="wb-score">{preflight.missing?.length?'需补充':'可执行'}</span>}</div>{!preflight&&<div className="wb-empty"><Bot/><strong>系统会在这里解释为什么匹配</strong><p>主任务只保留一个，其他命中项作为辅助任务依次执行。</p></div>}{preflight&&<div className="wb-route-list">{(preflight.routes||preflight.result?.routeSummary||[]).map((e:Row,i:number)=><div key={e.id}><b>{i+1}</b><span className="wb-entry-icon">{routeIcon(e.id)}</span><span><strong>{e.name}</strong><small>{e.role||'辅助任务'} · {e.id}</small></span><em>{e.completeness!==undefined?`${e.completeness}%`:'已执行'}</em></div>)}</div>}{(preflight?.missing?.length||0)>0&&<div className="missing-box"><AlertTriangle/><div><strong>缺少必要信息</strong><p>{preflight?.missing?.join('、')}。可继续生成待补充记录，补齐后重新执行。</p></div></div>}{preflight&&!preflight.missing?.length&&<div className="wb-ok"><ShieldCheck/><span><strong>必要信息检查通过</strong><small>结论仍需按风险等级进行人工复核</small></span></div>}</aside></div>
    {run&&<RunResult run={run} notify={notify} onChange={setRun}/>}
    <section className="panel wb-rule-strip"><strong>全局安全规则</strong>{config.rules.map((x:string)=><span key={x}><Check/>{x}</span>)}</section>
  </div>
}

function RunResult({run,notify,onChange}:any){const routes=run.result?.routeSummary||[];async function review(action:string){try{const r=await patch(`/runs/${run.id}`,{action});onChange(r);notify(action==='approve'?'人工复核已完成':'已驳回并标记待补充')}catch(e:any){notify(e.message)}}return <section className="panel wb-result"><div className="wb-result-head"><div><span className="wb-id">{run.id}</span><h3>{run.title}</h3><p>{routes.length} 个路由 · {run.steps?.length||0} 个步骤 · {dateTime(run.updatedAt)}</p></div><div><span className={`wb-status ${run.risk==='P0'?'danger':''}`}>{run.risk}</span><span className="wb-status">{run.status}</span></div></div><div className="wb-result-tabs">{routes.map((r:Row)=><span key={r.id}>{r.role} · {r.name}</span>)}</div>{routes.map((r:Row)=><article className="wb-output" key={r.id}><header><span className="wb-entry-icon">{routeIcon(r.id)}</span><div><strong>{r.name}</strong><small>引用范围：{r.knowledge?.join('、')||'无知识事实引用'}</small></div></header><pre>{JSON.stringify(run.result.sections?.[r.id],null,2)}</pre></article>)}<div className="wb-review"><div><ShieldCheck/><span><strong>人工复核</strong><small>{run.review?.note||'确认任务识别、证据、风险与结构化输出。AI 不做最终上线批准。'}</small></span></div><div><button className="button" onClick={()=>review('reject')}><X/>驳回补充</button><button className="button primary" onClick={()=>review('approve')}><Check/>确认通过</button></div></div></section>}

export function RunsPage({notify}:any){const [q,setQ]=useState(''),[status,setStatus]=useState(''),[data,setData]=useState<Row>({items:[],pages:1,total:0,page:1}),[selected,setSelected]=useState<Row|null>(null),[page,setPage]=useState(1);const load=()=>api(`/runs?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}&page=${page}&pageSize=20`).then(setData).catch(e=>notify(e.message));useEffect(()=>{void load()},[q,status,page]);async function open(id:string){setSelected(await api(`/runs/${id}`))}return <div className="page stack wb-page"><div className="page-intro"><div><span className="wb-kicker">TRACEABLE RUNS</span><h2>执行记录</h2><p>每次识别、路由、步骤、输入、证据与人工复核都可追溯。</p></div><button className="button" onClick={load}><RefreshCw/>刷新</button></div><div className="filterbar"><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索标题或原始输入"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option>待补充</option><option>待复核</option><option>已完成</option></select><span className="summary">共 {data.total} 条</span></div><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>执行记录</th><th>主任务</th><th>路由数</th><th>风险</th><th>状态</th><th>缺项</th><th>复核</th><th>更新时间</th></tr></thead><tbody>{data.items.map((r:Row)=><tr key={r.id} onClick={()=>open(r.id)}><td><strong>{r.title}</strong><small className="id">{r.id}</small></td><td>{r.mainRoute}</td><td>{r.routes.length}</td><td><WBadge value={r.risk}/></td><td><WBadge value={r.status}/></td><td>{r.missing.length}</td><td>{r.review?.status}</td><td>{dateTime(r.updatedAt)}</td></tr>)}</tbody></table></div><div className="pagination"><span>第 {page} / {data.pages} 页</span><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>‹</button><button disabled={page>=data.pages} onClick={()=>setPage(x=>x+1)}>›</button></div></section>{selected&&<div className="overlay"><div className="drawer wb-run-drawer"><header><div><span className="wb-kicker">RUN DETAIL</span><h2>{selected.title}</h2><small>{selected.id}</small></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></header><div className="drawer-body"><RunResult run={selected} notify={notify} onChange={setSelected}/><section className="detail-section"><h3>逐步执行轨迹</h3><div className="vertical-flow">{selected.steps.map((s:Row,i:number)=><div key={s.id}><span>{i+1}</span><span className="wb-mini-icon">{routeIcon(s.routeId)}</span><div><strong>{s.stepName}</strong><small>{s.routeId} · {dateTime(s.completedAt)}</small></div><WBadge value={s.status}/></div>)}</div></section></div></div></div>}</div>}

export function OrchestrationPage({notify}:any){const [items,setItems]=useState<Row[]>([]),[current,setCurrent]=useState<Row|null>(null),[draft,setDraft]=useState<Row>({});const load=()=>api('/assets').then((r:any)=>{setItems(r.items);if(!current&&r.items[0]){setCurrent(r.items[0]);setDraft(r.items[0])}});useEffect(()=>{void load().catch(e=>notify(e.message))},[]);function choose(x:Row){setCurrent(x);setDraft({...x,triggers:[...x.triggers],required:[...x.required],knowledge:[...x.knowledge],workflow:[...x.workflow]})}async function save(){try{const r=await patch(`/assets/${current?.id}`,draft);setCurrent(r);setDraft(r);await load();notify(`已发布 ${r.id} v${r.version}`)}catch(e:any){notify(e.message)}}const editList=(key:string,value:string)=>setDraft({...draft,[key]:value.split('\n').map(x=>x.trim()).filter(Boolean)});return <div className="page stack wb-page"><div className="page-intro"><div><span className="wb-kicker">WORKBENCH ASSETS</span><h2>工作台编排</h2><p>事实留在知识库；工作台只维护入口、触发词、表单、流程、引用映射与输出规则。</p></div><button className="button primary" onClick={save} disabled={!current}><Save/>保存并发布新版本</button></div><div className="wb-orchestration"><aside className="panel wb-asset-nav"><div className="panel-title"><div><h3>7 个标准入口</h3><p>点击编辑当前发布资产</p></div></div>{items.map(x=><button key={x.id} className={current?.id===x.id?'active':''} onClick={()=>choose(x)}><span className="wb-entry-icon">{routeIcon(x.id)}</span><span><strong>{x.name}</strong><small>{x.id} · v{x.version}</small></span><ChevronRight/></button>)}</aside>{current&&<section className="panel wb-asset-editor"><div className="wb-asset-title"><span className="wb-entry-icon">{routeIcon(current.id)}</span><div><span className="wb-id">{current.id}</span><h3>{current.name}</h3></div><WBadge value={current.status}/></div><div className="wb-edit-grid"><label className="field"><span>触发词（每行一项）</span><textarea value={(draft.triggers||[]).join('\n')} onChange={e=>editList('triggers',e.target.value)}/></label><label className="field"><span>必填信息（每行一项）</span><textarea value={(draft.required||[]).join('\n')} onChange={e=>editList('required',e.target.value)}/></label><label className="field"><span>知识库引用映射（每行一项）</span><textarea value={(draft.knowledge||[]).join('\n')} onChange={e=>editList('knowledge',e.target.value)}/></label><label className="field"><span>工作流步骤（严格顺序）</span><textarea className="wb-tall" value={(draft.workflow||[]).join('\n')} onChange={e=>editList('workflow',e.target.value)}/></label></div><div className="warning"><AlertTriangle/><p><strong>发布规则</strong><br/>知识库事实不复制到工作台；修改后版本号递增，历史执行记录保留当时快照。删除步骤前请确认不会破坏输出 Schema。</p></div></section>}</div></div>}

export function SandboxPage({notify}:any){const [items,setItems]=useState<Row[]>([]),[running,setRunning]=useState('');const load=()=>api('/validations').then((r:any)=>setItems(r.items)).catch(e=>notify(e.message));useEffect(()=>{void load()},[]);async function run(id:string){setRunning(id);try{const r=await post(`/validations/${id}`,{});notify(r.passed?'验证通过：路由与规则符合预期':'验证失败：请检查触发词与路由顺序');await load()}catch(e:any){notify(e.message)}finally{setRunning('')}}return <div className="page stack wb-page"><div className="page-intro"><div><span className="wb-kicker">VALIDATION SANDBOX</span><h2>案例验证</h2><p>用固定 walkthrough 验证路由、流程与安全规则，发布工作台资产前先回归。</p></div></div>{items.map(x=><section className="panel wb-validation" key={x.id}><div className="wb-validation-head"><div><span className="wb-id">{x.id}</span><h3>{x.name}</h3></div><WBadge value={x.status}/></div><div className="two-col"><div><h4>完整材料</h4><pre>{x.inputText}</pre></div><div><h4>预期检查</h4><div className="wb-chip-row">{x.expectedRoutes.map((id:string)=><span key={id}>{id}</span>)}</div><ul>{x.expectedRules.map((r:string)=><li key={r}>{r}</li>)}</ul>{x.lastResult?.checkedAt&&<p className="wb-last">最近验证：{dateTime(x.lastResult.checkedAt)} · 实际路由 {x.lastResult.actualRoutes?.join(' → ')}</p>}</div></div><button className="button primary" onClick={()=>run(x.id)} disabled={running===x.id}>{running===x.id?<Loader2 className="spin"/>:<Play/>}运行验证案例</button></section>)}</div>}

function WBadge({value}:any){const bad=['P0','失败','已驳回'].includes(value),ok=['已完成','通过','已发布','已复核'].includes(value);return <span className={`wb-status ${bad?'danger':ok?'success':''}`}>{value||'—'}</span>}
